language: generic
sudo: required
services:
- docker
env:
- GO111MODULES="on"
script:
- go test -mod=vendor ./chillybin ./jafflr ./tpi # <- run unit/functional tests // HL
- docker-compose up -d # <- prepare for integration tests
- docker-compose ps
- go test -mod=vendor -v ./integration-tests # <- run integration tests // HL
  # alternative: - docker-compose -f docker-compose.yml -f docker-compose.test.yml run test # <- run integration tests // HL
deploy:
  provider: script
  script: bash ./scripts/deploy.sh // HL
  on:
    branch: master
