language: generic
sudo: required
services:
- docker
env:
- GO111MODULES="on"
script:
- go test -mod=vendor ./chillybin ./jafflr ./tpi # <- run unit/functional tests // HL
- docker-compose up -d # <- prepare for integration tests
- go test -mod=vendor -v ./integration-tests # <- run integration tests // HL
- bash ./scripts/publish.sh # <- scripted because monorepo // HL
deploy:
  provider: script
  script: bash ./scripts/deploy.sh prod # <- 'tag as prod' for now // HL
  on:
    branch: master
